FROM golang:1.15-alpine as dev

WORKDIR /work

FROM golang:1.15-alpine as build

WORKDIR /dapp
COPY ./dapp/* /dapp/
RUN go build -o dapp

FROM alpine as runtime 
COPY --from=build /dapp/dapp /
CMD ./dapp